type MessageData = {
    id: number;
    message: string;
    sender: string;
    timestamp: string;
    subject: string;
    unread: boolean;
    starred: boolean;
  };
  
  export const data: MessageData[] = [
    {
      id: 1,
      message: "Hello this is your boyu",
      sender: "John",
      timestamp: "2023-11-12T10:00:00Z",
      subject: "hello user",
      unread: true,
      starred: false,
    },
    {
      id: 2,
      message: "Meeting rescheduled to 3 PM",
      sender: "Alice",
      timestamp: "2023-11-12T11:00:00Z",
      subject: "Schedule Update",
      unread: true,
      starred: false,
    },
    {
      id: 3,
      message: "Project report due tomorrow",
      sender: "Bob",
      timestamp: "2023-11-12T12:00:00Z",
      subject: "Reminder",
      unread: true,
      starred: false,
    },
    {
      id: 4,
      message: "New client onboarding next week",
      sender: "Emma",
      timestamp: "2023-11-12T13:00:00Z",
      subject: "Client Update",
      unread: true,
      starred: false,
    },
    {
      id: 5,
      message: "Team building event on Friday",
      sender: "Mike",
      timestamp: "2023-11-12T14:00:00Z",
      subject: "Event Announcement",
      unread: true,
      starred: false,
    },
    {
      id: 6,
      message: "System maintenance scheduled",
      sender: "IT Dept",
      timestamp: "2023-11-12T15:00:00Z",
      subject: "Downtime Notice",
      unread: true,
      starred: false,
    },
    {
      id: 7,
      message: "Quarterly review results",
      sender: "HR",
      timestamp: "2023-11-12T16:00:00Z",
      subject: "Performance Update",
      unread: true,
      starred: false,
    },
    {
      id: 8,
      message: "New feature deployment successful",
      sender: "Dev Team",
      timestamp: "2023-11-12T17:00:00Z",
      subject: "Deployment Update",
      unread: true,
      starred: false,
    },
    {
      id: 9,
      message: "Budget approval needed",
      sender: "Finance",
      timestamp: "2023-11-12T18:00:00Z",
      subject: "Urgent Request",
      unread: true,
      starred: false,
    },
    {
      id: 10,
      message: "Office closed for holiday",
      sender: "Admin",
      timestamp: "2023-11-12T19:00:00Z",
      subject: "Holiday Notice",
      unread: true,
      starred: false,
    },
    {
      id: 11,
      message: "Client feedback received",
      sender: "Support",
      timestamp: "2023-11-12T20:00:00Z",
      subject: "Feedback Summary",
      unread: true,
      starred: false,
    },
    {
      id: 12,
      message: "New hire orientation next Monday",
      sender: "HR",
      timestamp: "2023-11-12T21:00:00Z",
      subject: "Onboarding",
      unread: true,
      starred: false,
    },
    {
      id: 13,
      message: "Emergency drill at 2 PM today",
      sender: "Safety Officer",
      timestamp: "2023-11-12T22:00:00Z",
      subject: "Safety Alert",
      unread: true,
      starred: false,
    },
    {
      id: 14,
      message: "Software license expiring soon",
      sender: "IT Dept",
      timestamp: "2023-11-12T23:00:00Z",
      subject: "License Renewal",
      unread: true,
      starred: false,
    },
    {
      id: 15,
      message: "Team lead position open",
      sender: "HR",
      timestamp: "2023-11-12T24:00:00Z",
      subject: "Job Opening",
      unread: true,
      starred: false,
    },
    {
      id: 16,
      message: "Quarterly sales report",
      sender: "Sales Dept",
      timestamp: "2023-11-12T25:00:00Z",
      subject: "Sales Update",
      unread: true,
      starred: false,
    },
    {
      id: 17,
      message: "New office equipment arrived",
      sender: "Admin",
      timestamp: "2023-11-12T26:00:00Z",
      subject: "Equipment Update",
      unread: true,
      starred: false,
    },
  ];